name: Flask App Build and Deploy

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }} 

jobs:
  build-deploy-main:
    runs-on: ubuntu-latest
    environment: farmers-note-backend

    steps:
      - name: â¬‡ï¸ Checkout source code
        uses: actions/checkout@v3
      
      - name: ğŸ”‘ Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ³ Build & Push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: ğŸš€ Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # EC2 ì„œë²„ ë‚´ ì‘ì—… ë””ë ‰í† ë¦¬ ì„¤ì •
            DEPLOY_DIR="/opt/farmersnote"
            sudo mkdir -p $DEPLOY_DIR
            cd $DEPLOY_DIR
            
            echo "Pulling latest image: ${{ env.IMAGE_NAME }}"
            sudo docker compose pull
            
            # Docker Compose ì„œë¹„ìŠ¤ ì¤‘ë‹¨, ì¬ìƒì„± ë° ì‹œì‘
            sudo docker compose up -d --remove-orphans
            
            echo "ğŸ‰ Flask ì„œë¹„ìŠ¤ ë°°í¬ ë° ì¬ì‹œì‘ ì™„ë£Œ!"